site_name: Конспект по ОПИ
site_url: https://artem961.github.io/exam-opi-notes/

theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Тёмная тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Светлая тема
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

plugins:
  - search:
      lang:
        - ru
        - en

extra_css:
  - stylesheets/extra.css

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
