site_name: Конспект к экзамену
# Project Pages: https://<username>.github.io/<repo>/  — подставь свой USERNAME (и repo, если не notes)
site_url: https://artem961.github.io/exam-opi-notes/

theme:
  name: material
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Тёмная тема
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Светлая тема
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true

plugins:
  - search:
      lang: ru          # русская морфология поиска — критично для билетов

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
